graphile/worker

package.json

I began to debug the error 
```
TypeError: Promise.all(...).finally is not a function
``` 
after a worker shutdown, when I realized that Promise.finally had been introduce in Node 10. This PR documents this in the engines field.

node 10 required in engines

---

README.md
__tests__/main.runAllJobs.test.ts
__tests__/main.start.test.ts
src/cli.ts
src/config.ts
src/interfaces.ts
src/main.ts
src/worker.ts

* #4 
* In order to pass the `--idle-delay` value down to the worker, I introduced a `WorkerOptions` object. I suspect there could be more options to come.
* I tried to write tests - but no avail so far. I tried to trap the `idleDelay` option by using Jest timer mocks (https://jestjs.io/docs/en/timer-mocks.html) but I could not get it to work as expected.
* Maybe we can agree on the implementation first (or reject it) and then I can tackle the tests again.

make idle delay configurable

---

src/runner.ts

* #22 
* The process does not exit anymore in case of a backend restart - but there is a Promise Rejection Warning:
```
1|worker  | (node:64357) UnhandledPromiseRejectionWarning: Error: Client has encountered a connection error and is not queryable
1|worker  |     at process.nextTick (.../node_modules/pg/lib/client.js:521:25)
1|worker  |     at process._tickCallback (internal/process/next_tick.js:61:11)
1|worker  | (node:64357) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
1|worker  | (node:64357) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise …
```

Add pgPool 'error' handler

---

__tests__/helpers.ts
__tests__/runner.runOnce.test.ts
src/runner.ts

* This replaces the stale PR #20 and fixes #17
* Added some tests for the options processing in form of `runner.runOnce.test`

Allow DATABASE_URL env variable, #17

---

README.md

This is how I fixed the issue on an old database that has extensions installed in another schema. Not sure if this is really a nice/elegant way of fixing this.
Maybe I should list the used functions, or link to an external file/readme with the code or solution to fix this? I don't really want to pollute the main readme with edge cases.
What's your thought on the best place to put this info?

How to solve issue when extensions aren't in public

---

README.md

* Async/Await full example
* use `require` instead of `import` like in the other examples
Fixes #14

Remove root level await in quickstart

---

__tests__/helpers.ts
__tests__/main.runTaskList.test.ts
__tests__/runner.runOnce.test.ts
src/helpers.ts

They still need to move to the new logging system, but at least their old code should still run.

fix(helpers): add `debug` helper for vague backwards compatibility

---

examples/README.md
examples/worker-cloud-tasks-exporter/README.md
examples/worker-cloud-tasks-exporter/tasks/cloud-tasks-exporter.js

Example code on how to delegate to GCP Cloud Tasks. Follows Faktory example template.

docs(examples): delegation to GCP Cloud Tasks

---

README.md

add a snippet for calling graphile_worker.add_job with a parameterized query with delayed execution

docs(README): interval multiplication example

---

src/runner.ts

The boolean check was reversed in determining if the runner was already running.
If it is already running and runner.stop() is called, it should release. Else it wasn't running when runner.stop() was called and it show throw.

fix: runner.stop() should now work

---

README.md
__tests__/main.runTaskList.test.ts
__tests__/main.runTaskListOnce.test.ts
__tests__/migrate.test.ts
sql/000002.sql
src/deferred.ts

See proposal and discussion in #61
Running the existing performance test script shows no impact from these changes - running in Docker (see #64) and repeated 3 times for each case, the average latency was ~2ms each time and total time to run jobs ~30s.
There was some discussion over whether this should be implemented as a unique partial index, since it is likely to contain a lot of null values. This would mean we couldn't use an `on conflict` clause when inserting though, so I've used a regular unique constraint
---
Closes #58 
Closes #59 
Closes #61

feat: allow existing jobs to be updated and removed

---

src/worker.ts

Also avoids fetching the record for fail_job / complete_job which saves on the parsing cost in node-postgres.
We could optimise this further by only pulling down the required Job fields, but this'd be a breaking change so I've not included it.

perf: use prepared statements

---

src/helpers.ts
src/interfaces.ts

Allows passing `jobKey` option to the `addJob` helper

feat: include jobKey in TaskOptions

---

package.json
yarn.lock

It's a stub, and no longer needed.

Remove @types/chokidar

---

.eslintignore
.eslintrc.js
.prettierrc.js
__tests__/fixtures/tasksFile_default.js
__tests__/getTasks.test.ts
__tests__/helpers.ts
__tests__/main.runTaskList.test.ts
__tests__/main.runTaskListOnce.test.ts
__tests__/migrate.test.ts
__tests__/runner.runOnce.test.ts
__tests__/workerUtils.addJob.test.ts
__tests__/workerUtils.completeJobs.test.ts
__tests__/workerUtils.permanentlyFailJobs.test.ts
__tests__/workerUtils.rescheduleJobs.test.ts
examples/README.md
examples/worker-cloud-tasks-exporter/README.md
examples/worker-cloud-tasks-exporter/tasks/cloud-tasks-exporter.js
package.json
src/cli.ts
src/getTasks.ts
src/helpers.ts
src/interfaces.ts
src/lib.ts
src/main.ts
src/migrate.ts
src/module.ts
src/runner.ts
src/worker.ts
src/workerUtils.ts
yarn.lock

- order imports
- lint more files
- don't run prettier inside ESLint
- use `.eslintignore` for both ESLint and Prettier

chore: lint improvements

---

README.md

A very warm welcome to our new Featured Sponsors: Postlight and Qwick. Qwick are our first Project Sponsor, choosing Graphile Worker as their project of choice ❤️
@benjie feel free to change up the footnote

sponsorship: Welcome to our new Featured Sponsors

---

src/worker.ts

In the case that a worker task throws a poorly formed error (one without a `message` property), the error message prints but the query that would fail the job does not complete.  This leaves the job not running but still occupying the queue.

fix: use default message when task rejects with non-Error object

---

README.md

This PR adds a quick note about the error that is output to the Postgres logs when the worker schema does not yet exist.
Discussed with @benjie here: https://github.com/graphile/worker/pull/115#issuecomment-634637412

docs(README): add note about PostgreSQL schema error

---

__tests__/fixtures/blah.js
__tests__/fixtures/tasks/wouldyoulike.js
src/getTasks.ts
src/module.ts

Previously in watch mode, if your task were to require an external module, that module would be cached in perpetuity using Node's `require()` cache, so modifications to it would not show up.
This PR changes behaviour so that it is "fauxRequire" all the way down, i.e. if you change the task then it will re-require a fresh version of all its dependencies.
**NOTE**: it does **NOT** watch other files, so you still need to modify the task itself to trigger a reload.
**NOTE**: with this enabled, other modules are **not shared**, so if taskA and taskB each `require('../shared')`, they will each get different instances of that module. This is **only true in watch mode**, so look out for inconsistencies from this.

fix(watch): don't cache external modules

---

src/cli.ts
src/interfaces.ts
src/worker.ts

From pgBouncer FAQ:
> ## How to use prepared statements with transaction pooling?
> To make prepared statements work in this mode would need PgBouncer to keep track of them internally, which it does not do. So only way to keep using PgBouncer in this mode is to disable prepared statements in the client.
Passing flag `--no-prepared-statements` or option `noPreparedStatements: true` will prevent Graphile Worker using prepared statements, for compatibility with pgBouncer and other software.
Fixes #119

feat(sql): allow avoiding prepared statements

---

.github/workflows/ci.yml
__tests__/schema.sql
package.json
scripts/dump_db
yarn.lock

This PR adds a `yarn db:dump` command that dumps the schema to `__tests__/schema.sql`. This dumped schema differs from `pg_dump` in that it removes all lines that start `--` (i.e. pg_dumps comments) because it makes it more likely the dump will be stable across PostgreSQL versions (although we only care it's stable on CI). It also removes blank or whitespace only lines (even inside of functions) for the same reason. It's not intended to be used for anything other than as a PR review tool to make database schema differences more obvious.

chore: track schema changes

---

README.md
RELEASE_NOTES.md
__tests__/helpers.ts
__tests__/runner.runOnce.test.ts
src/cli.ts
src/lib.ts

Fixes #50
We defer to Pool to process the envvars; we just check that there's at least a `PGDATABASE` envvar because we don't want to overwrite the default database by accident.

feat: add support for standard PostgreSQL PG* envvars

---

src/module.ts

Fixes #145; the module cache was being written to at too late a stage, causing cyclic requires to trigger an infinite loop. This PR fixes this by caching the module _before_ we execute the module, meaning the cache is in place before the module can require other modules which might in turn require this module again.
(We fixed this on stream.)

fix(watch): solve bug with cyclic requires

---

perfTest/run.js

Important to know if scheduling jobs becomes slower.
None.
None.

chore(perfTest): time scheduling jobs

---

__tests__/migrate.test.ts
__tests__/schema.sql
sql/000006.sql

Adds an index to improve the performance of job discovery when there are a few thousand failed or locked jobs.
I'm not sure if this is a change that is desirable for all users, but it is for us so I thought it would be at least worth opening a PR (even if it will just be kept closed) so that others who may have the problem can find this solution.
On my machine (Macbook Pro 2017, 2.8 GHz Quad-Core Intel Core i7), this has no impact on `yarn perfTest`.
In production on several deployments, this dramatically speeds up `graphile_worker.get_job` when the number of jobs in a permanently failed state or locked / abandoned state increases above a few thousand. When this happens, `graphile_worker.get_job` becomes responsible for 90% of database CPU on a large (30 vCPU) database sequentially …

feat(perf): extend index with `locked_at` and make partial

---

README.md
__tests__/events.test.ts
examples/readme/README.md
examples/readme/events.js
examples/readme/tasks/task_2.js
src/interfaces.ts
src/lib.ts
src/main.ts
src/runner.ts
src/signals.ts
src/worker.ts

There's lots of events that happen inside of Graphile Worker that library consumers might be interested in; this PR raises these events with an event system.
**IMPORTANT**: people registering event handlers **MUST** make sure that these handlers do **NOT** throw errors. We've wrapped the `emit` with a try/catch that swallows the error in the two most dangerous places, but consumers must be certain that errors are not thrown as this may cause unexpected states of the work queue to take place.
Events added so far:
- `pool:create` - When a worker pool is created
- `pool:listen:connecting` - When a worker pool attempts to connect to PG ready to issue a LISTEN statement
- `pool:listen:success` - When a worker pool starts listening for jobs via PG LISTEN
- `pool:listen:error` - When a worker …

feat(events): add events system

---

.github/workflows/ci.yml

Doesn't make sense to run the linting in all the different environments.

chore(ci): separate linting into its own action

---

README.md
__tests__/events.test.ts
src/interfaces.ts
src/worker.ts

Event just before get_job and just after fail_job/complete_job
Negligible.
None.

feat(events): add more events

---

README.md
examples/readme/events.js

If you use the worker in library mode and you have an issue whereby a job cannot be released (marked as success or failure) then the entire worker will exit with a fatal error. You should await `runner.promise` so that you know about this; and on error you can take the appropriate action (logging the error, restarting the worker, exiting the process, whatever makes sense for you).

docs(README): note about awaiting runner.promise

---

.github/workflows/ci.yml

No need, and on lint error it makes it seem altschema has issues too (misleading).

chore(ci): don't lint altschema

---

perfTest/b.js
perfTest/n.js

Just seeing `a is 3`, `n is 8` logged is kinda useless. This improves those logging messages.

chore(perfTest): solve confusion via logging++

---

README.md
src/cli.ts
src/getCronItems.ts

Graphile Starter uses `dist/tasks/*.js` for tasks, because the original tasks are written in TypeScript and worker doesn't (currently) support loading tasks in anything but native JS. Putting the crontab file in `dist` feels very wrong; putting it in `src` and copying it seems like a pain, and using a symlink is not cross-platform enough (and further may not support watch mode well). I decided the best way to deal with this would be to let you override the path to the crontab.
Negligible.
None known.

feat(cli): --crontab option to give alternative crontab path

---

README.md
RELEASE_NOTES.md
__tests__/helpers.ts
package.json
src/logger.ts
yarn.lock

Trying to standardize on one logging framework across the stack; so I've extracted out the worker logger into a new library which I've enhanced and documented better:
https://github.com/graphile/logger
This PR ports this new library back into worker :grin: 
Negligible.
None known.

feat: switch out custom logger with @graphile/logger

---

RELEASE_NOTES.md
src/lib.ts

If an error occurred on a client that was checked out from the pool when the client wasn't being actively used (e.g. the server terminated the client, the network timed out, etc) then the client would emit the `error` event. For long running clients we register an error handler to catch this, but it seems that short running clients can also be vulnerable to it under the right conditions.
Fixes #178.
Negligible.
Fixes a potential unexpected server exit.

fix(errors): more thorough error handling

---

RELEASE_NOTES.md
package.json
yarn.lock

Should match our `pg` version range.
None.
None.

chore(deps): support wider range of @types/pg

---

RELEASE_NOTES.md
src/logger.ts

We accidentally turned the `Logger` export into a type-only export. This fixes that regression.
Fixes #192 
None.
None.

fix: restore Logger export

---

README.md

Fix doc typo in readme. "nohandleSignals" should be "noHandleSignals".
N/A
N/A

fix(docs): "nohandleSignals" => "noHandleSignals"

---

src/crontab.ts
src/index.ts

Exposes separate `parseCronItem` helper for parsing an individual cron item.
Separates refactoring work out of #213.
Negligible additional startup cost.
None known.

feat: expose parseCronItem function

---

__tests__/cron.test.ts
src/cron.ts
src/cronConstants.ts
src/cronMatcher.ts
src/crontab.ts
src/interfaces.ts

This PR is made of 4 separate commits:
1. **Move TimestampDigest into interfaces**
This should always have been in the interfaces file.
*Change:* this results in TimestampDigest being export; previously it was not. *No other changes to exported interface or functionality.*
2. **Move regexps and constants out of crontab into a common file**
It's important that the cron regexps remain together so that they will not diverge over time, however it's desirable to be able to use them in different files in future (e.g. #219) so I've moved them to a common file that can be imported from the files that need it.
*No change in exported interface or functionality.*
3. **Extract `cronItemMatches` to new file**
In the future (e.g. #219) it's likely that parsing/matching a cron expression (`* * * * *`) …

chore(refactor): split some cron code into new files to ease maintenance

---

src/main.ts

Graceful shutdown does not unlock jobs with no `queue` assigned.
NA
NA

fix(shutdown): properly release jobs with no queue assigned

---

src/main.ts

First of all, thank you for your library. I discovered a bug today.
The callback passed to `pool.connect(callback)` [in this case](https://github.com/brianc/node-postgres/blob/master/packages/pg-pool/index.js#L166) will only be called with an error. Therefore, `releaseClient` can be undefined.
n/a
n/a

fix: handle errors when releasing worker

---

src/crontab.ts
src/getTasks.ts
src/migrate.ts

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
From past experience there is no performance impact due to switching to slice()
None as the returned values are still the same

chore: replace deprecated String.prototype.substr()

---

README.md
RELEASE_NOTES.md
src/runner.ts

Fixes #262.
There's a bug in `runner` where it does not expose the promise returned from `cron` to the user; as such the user has no way to handle errors that happen in cron (or even to know if an error did happen) - instead the worker would just continue on regardless, but with cron not running. In Node v16+ this behavior changes, and instead the unhandled rejection will crash the entire process. Neither of these solutions are ideal...
This PR changes the error handling, making it so that errors raised from cron are also returned via the `promise` property. Further, it refactors to make the synchronous nature of the error handling more obvious. And further still, it makes it so that an error in cron will shut down the worker and vice versa.
Negligible.
More resilient to backend issues ─ …

fix(cron): avoid unhandled rejection

---

README.md
RELEASE_NOTES.md
__tests__/migrate.test.ts
__tests__/schema.sql
sql/000012.sql
src/interfaces.ts
src/sql/failJob.ts
src/worker.ts

Sometimes you want to append data to a scheduled job, but currently we only allow replacing the payload via `job_key`. Sometimes you want to process data in a batch, but we currently only allow creating or replacing jobs, and we only run them one at a time.
This PR solves both of these issues with on solution: "batch jobs." The concept is pretty simple (as is the code thanks to the previous work in #274) - we allow a job payload to be an array, and if it is indeed an array then when you use a `job_key` instead of replacing the payload, we'll merge it (the new items will be appended to the previous list).
When it comes time to execute the task, it'll work as it did previously, _except_ you can optionally return a list of promises from your task if it's processing a batch job. If you do so …

feat: batch jobs

---

RELEASE_NOTES.md
__tests__/main.runTaskListOnce.test.ts
__tests__/migrate.test.ts
__tests__/schema.sql
sql/000013.sql
src/cron.ts
src/helpers.ts
src/runner.ts
src/sql/failJob.ts

Since 0.13.0 we've made some significant changes to the DB (but not released them). On review, it turns out that we hadn't completed some of these changes (for example the `priority` was `smallint` in the jobs table, but still `int` in the function parameters), so this tidies that up and gets the `RELEASE_NOTES` ready for release.
Negligible.
None known.

fix: inconsistencies in SQL schema

---

src/sql/resetLockedAt.ts

Unlikely to affect anyone, but this ensures if you're using a mixture of node-time and not-node-time (why would you do that?) that no conflicts occur

fix: factor useNodeTime into prepared statement name

---

RELEASE_NOTES.md
src/sql/resetLockedAt.ts

Imagine we have a number of jobs (say for example twice our `concurrency` setting's worth) that hang indefinitely. Our queue looks like it's not progressing. After 4 hours, those jobs will be unlocked, and because their run_at is unchanged, they will still be front of the queue. When a worker becomes available they will be re-attempted before any other tasks. Thus this locked situation might persist indefinitely.
When we reset the `locked_at`/`locked_by` of jobs that were locked 4+ hours ago, we should _also_ update the `run_at` to ensure that any jobs queued in the interrim can be attempted first, since this is already defacto a failed job.
Fixes potential locked job queue situation.
Fixes potential locked job queue situation.

fix: unlocked jobs should have run_at bumped to now()

---

RELEASE_NOTES.md
perfTest/latencyTest.js

Fixed 2 random typos (this was a trial run for [a CLI I made](https://github.com/Lioness100/rspell))
unknown
unknown

docs: fix typos

---

README.md
RELEASE_NOTES.md
__tests__/main.runTaskListOnce.test.ts
__tests__/migrate.test.ts
__tests__/schema.sql
sql/000014.sql
src/cron.ts
src/helpers.ts
src/sql/completeJob.ts
src/sql/failJob.ts
src/workerUtils.ts

This does _not_ change the underlying data in the jobs table, instead it just restores the old `add_job` signature so that `add_job('foo', priority => 7)` works without needing a `::smallint` cast.
This does **not** change the `add_jobs` signature - you must cast to `smallint` to use that - we see that method a performance critical, so no unnecessary casting.
Trivially small casting cost from `::int` to `::smallint` inside the `add_job` and `reschedule_jobs` functions.
None known.
Fixes #319

Change `add_job` signature back to using `int` instead of `smallint`

---

README.md

Simple doc update to point out that Graphile Worker expects the tables to be owned by Postgres role that you use at runtime, as discussed in the Discord channel!
None
None

docs: add some info regarding pg roles

---

README.md
RELEASE_NOTES.md
__tests__/main.runTaskList.test.ts
__tests__/resetLockedAt.test.ts
perfTest/latencyTest.js
src/interfaces.ts
src/main.ts
src/runner.ts

Previously we claimed that a graceful shutdown would wait for jobs to complete; but it didn't.
Previously we had a `.release()` method and a `.gracefulShutdown()` method on worker pools... But these were badly named. Really `.release()` was the graceful shutdown (would wait for jobs to complete), and `.gracefulShutdown()` was more of a forceful shutdown (would "fail" all active jobs).
This PR:
- Deprecates `workerPool.release()` in favour of `workerPool.gracefulShutdown()`
- Fixes `workerPool.gracefulShutdown()` to shut down gracefully (waiting for jobs to complete)
- Adds `workerPool.forcefulShutdown()` to "fail" the running jobs and force-release the pool
- Fixes handling of signals:
- First termination signal triggers graceful shutdown
- Signal over next 5 seconds are ignored
- Second …

Fix gracefulShutdown and introduce forcefulShutdown

---

.eslintignore
RELEASE_NOTES.md
__tests__/cron-timing.test.ts
src/config.ts
src/index.ts
src/lib.ts
src/worker.ts

`maxContiguousErrors` was not fit for purpose, it needs to be properly planned and designed before being reintroduced.
Fixes #307
None.
None known.

Remove maxContiguousErrors

---

RELEASE_NOTES.md
__tests__/main.runTaskList.test.ts
src/main.ts

If you cleanly shut down a worker, we shouldn't need the global event listeners any more. This PR removes them (but only when you shut down via the API - a shutdown via SIGTERM/SIGINT/etc is expected to terminate the process).
Fixes #305.
Marginal increase on boot up and shutdown.
None known.

Unregister signal handlers on worker shutdown

---

RELEASE_NOTES.md
__tests__/migrate.test.ts
src/migrate.ts

Checks that the current DB revision isn't higher than the revisions the current worker supports.
Fixes #280 
Negligible.
None known.

Assert that database schema isn't more up to date than current worker

---

RELEASE_NOTES.md
src/cli.ts
src/main.ts
src/migrate.ts
src/runner.ts
website/docs/error-handling.md

When a new version of Graphile Worker that contains new migrations executes, it is likely unsafe for existing workers to continue to run since they no longer understand the schema. This PR has the new worker announce the migration and existing workers detect this (via a `NOTIFY` event; which is not a 100% reliable means of communication but should be fine for this) and shut down gracefully.
Fixes #175
Negligible.
If someone can issue `NOTIFY "jobs:migrate";` on the database then they can cause all Graphile Worker instances to shut down gracefully. This is deemed to not be a security vulnerability since Graphile Worker explicitly trusts that only authorized people will be able to trigger notifications on the database.

Detect migrations and shut down

---

RELEASE_NOTES.md
__tests__/events.test.ts
__tests__/getTasks.test.ts
__tests__/helpers.ts
__tests__/main.runTaskList.test.ts
__tests__/resetLockedAt.test.ts
src/interfaces.ts
src/workerUtils.ts
website/docs/library/add-job.md
website/docs/typescript.md

Fixes #142
Fixes #57
Fixes #150
Fixes #237
Fixes #56
For anyone involved in the above issues/PRs, you may know that I've been extremely hesitant to change the payload type from `unknown` to a concrete user-defined type. The main reason for this is that there are no guarantees that `payload` will actually conform to the runtime type because a) it might have been populated by an older runtime (with different types), or b) it might have been populated by something that doesn't even use TypeScript - e.g. a database trigger. Nonetheless, it has been a common request, and I think people are generally okay with the warnings, and know that if they get burned by these assumptions then that's on them. As such, I've finally made the decision to add generic types.
To do so, I've added a central …

Make tasks generic

---

.github/workflows/ci.yml
RELEASE_NOTES.md
__tests__/fixtures-esm/blah.js
__tests__/fixtures-esm/package.json
__tests__/fixtures-esm/tasks/wouldyoulike.js
__tests__/fixtures-esm/tasks/wouldyoulike_default.js
__tests__/fixtures-esm/tasksFile.js
__tests__/fixtures-esm/tasksFile_default.js
__tests__/getTasks.test.ts
package.json
src/getTasks.ts
website/docs/requirements.md

Fixes #226.
Now we don't have watch mode and we support minimum Node 18, supporting ESM is more straightforward.
Negligible.
Unknown.

Add support for importing ESM files

---

RELEASE_NOTES.md
__tests__/cron.test.ts
__tests__/helpers.ts
__tests__/main.runTaskListOnce.test.ts
__tests__/migrate.test.ts
__tests__/resetLockedAt.test.ts
__tests__/schema.sql
__tests__/workerUtils.forceUnlockWorkers.test.ts
perfTest/init.js
perfTest/latencyTest.js
sql/000016.sql
src/cron.ts
src/generated/sql.ts
src/sql/completeJob.ts
src/sql/failJob.ts
src/sql/getJob.ts
src/sql/resetLockedAt.ts
src/taskIdentifiers.ts
website/docs/glossary.md
website/docs/scaling.md
website/docs/schema.md

Renames all tables to `_private_*` to make it clear that users should not rely on their shapes.
The tables were already private interfaces so this is not technically a breaking change; however it's likely that a small proportion of users were reading from these tables so we'll count it as one anyway.
Negligible (slightly longer table names, using aliases in SQL).
None known.

Rename tables to make privacy clear

---

RELEASE_NOTES.md
__tests__/helpers.ts
__tests__/jobsView.test.ts
__tests__/migrate.test.ts
__tests__/schema.sql
sql/000017.sql
src/generated/sql.ts
src/interfaces.ts
website/docs/jobs-view.md
website/docs/schema.md

Adds a public `graphile_worker.jobs` view that can be selected from. It is not recommended to use this since it has performance overhead, but it's better to use it than to read from the underlying tables.
Should not have any impact unless the view is used. We recommend that you only use the view when essential, and that you don't poll it frequently.
Since it's a view it does bypass the row-level security policies on the underlying tables, but the `payload` has been removed so this is unlikely to cause a significant security issue. We aren't using security barrier because this would require us to bump the minimum supported version of Postgres. We do not `GRANT` any access to this view, so most roles should get permission denied errors when they attempt to select from it, depending on the …

Add a 'jobs' view that people can select from

---

Dockerfile.dev

fixes `docker-compose up -d`  by adding `./scripts` to dev container so prepack can build sql artifacts
```
=> ERROR [app 12/12] RUN yarn prepack                                                                                                  1.0s 
------
> [app 12/12] RUN yarn prepack:
0.397 yarn run v1.22.19
0.441 $ rm -Rf dist && npm run build:sql && tsc && chmod +x dist/cli.js
0.871
0.871 > graphile-worker@0.15.1 build:sql
0.871 > node ./scripts/buildSqlModule.mjs
0.871
0.912 node:internal/modules/cjs/loader:1080
0.912   throw err;
0.912   ^
0.912
0.912 Error: Cannot find module '/app/scripts/buildSqlModule.mjs'
0.912     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
```
-
-

fix `docker-compose up -d`

---

RELEASE_NOTES.md
__tests__/migrate.test.ts
__tests__/schema.sql
perfTest/run.js
sql/000018.sql
src/generated/sql.ts
src/lib.ts
src/main.ts

Previously if you called `add_jobs()` and passed in 100 jobs, the `jobs:insert` announcement would only be made once, resulting in only one idle worker being triggered. i.e. the first of these 100 jobs would start straight away, but the rest would only start once the other workers' poll interval ticked.
Now we add the count of the number of jobs queued to the announcement, and we keep nudging workers to look at the job until either there are no more available workers or we've nudged at least this many workers.
There was a performance cost on the queuing side (according to my benchmarks, queuing time could increase by up to 5%) so I've overhauled how queueing works to remove a trigger call and thus the net change is close to zero.
None known.

When queuing multiple jobs at once, nudge more than one worker

---

__tests__/getTasks.test.ts
__tests__/helpers.ts
__tests__/migrate.test.ts
src/cron.ts
src/getTasks.ts
src/helpers.ts
src/index.ts
src/interfaces.ts
src/lib.ts
src/main.ts
src/migrate.ts
src/runner.ts
src/worker.ts
src/workerUtils.ts

In particular working towards values being pulled more consistently from presets.
Slight improvement in places? Marginal at best.
None known.

Reduce calls to processSharedOptions by passing pre-processed values more consistently

---

__tests__/schema.sql
sql/000018.sql
src/generated/sql.ts

Postgres docs for NOTIFY state:
> Except for dropping later instances of duplicate notifications, NOTIFY guarantees that notifications from the same transaction get delivered in the order they were sent. It is also guaranteed that messages from different transactions are delivered in the order in which the transactions committed.
Therefore, something like:
```sql
BEGIN;
select add_job(...);
select add_job(...);
select add_job(...);
COMMIT;
```
Might result in 3 identical notifications `NOTIFY "jobs:insert", '{"count":1}';` which would be de-duplicated.
To avoid this deduplication, I've added a random number to each payload.
Marginal cost on job insertion.
None known.

Add random number to notify payload to prevent deduplication

---

website/docs/pro/config.md
website/docs/pro/index.md
website/docs/pro/recovery.md

If a regular Graphile Worker process exits unexpectedly (for example someone pulls the power lead from the server, or the Node.js process crashes or is killed) it does not have a chance to unlock its active jobs, and they remain locked for up to 4 hours. For some jobs, not being attempted again for 4 hours could be far too long.
[Worker Pro](https://worker.graphile.org/docs/pro) tracks running workers via a &ldquo;heartbeat&rdquo;, and when a worker has not checked in for a configurable amount of time we can assume that this worker is no longer active (crashed, was terminated, server shut down, etc) and release its jobs back to the pool to be executed (honouring [exponential backoff](../exponential-backoff.md) to help avoid crashes from poorly written task executors causing worker …

Pro: document worker recovery features

---

perfTest/tasks/nested/folder/python.py

Don't parse the JSON before you check it's JSON.
None.
Improvement?

perfTest example: move python validation earlier

---

website/docs/library/add-job.md
website/docs/typescript.md

Some documentation tweaks:
- `addJob()` example now mirrors the example on the "Add jobs through SQL" page
-  changed `payload` to `unknown` type with an explanation, on the same `AddJob()` page
- Reordered the TypeScript page to put the recommended route at the top
- Added an Amazon SES example to the TypeScript page
Docs only
Docs only
- ~~[ ] I've added tests for the new feature, and `yarn test` passes.~~
- ~~[ ] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).~~
- ~~[ ] If this is a breaking change I've explained why.~~

website: Docs tweaks to AddJob and TypeScript pages

---

website/docs/library/add-job.md

The definition says maxAttempts minimum is 1 in which case the task will only be attempted once and won't be retried.
None
None

Fix documentation on maxAttempts to match definition

---

RELEASE_NOTES.md
__tests__/fixtures/tasks/wouldyoulike_ts.js
__tests__/fixtures/tasksFile-ts.js
__tests__/fixtures/tasksFile_default-ts.js
__tests__/getTasks.test.ts
src/getTasks.ts
src/plugins/LoadTaskFromJsPlugin.ts

Fixes #416; namely TypeScript modules that are output in CommonJS mode lead to `const rawMod = await import(file)` returning something like `{ __esModule: true, default: { __esModule: true, default: <the default export> } }` which is super weird.
Marginal cost in task loading, no further runtime overhead.
None known.

Fix ESM woes

---

src/worker.ts

This change fixes https://github.com/graphile/worker/issues/418, which was a simple bug introduced where the `workerId` was no longer being set on the logger scope (it was being set on a nested `scope` property), which resulted in the default logger not outputting as expected, and the `logFactory` function not being passed the values as defined in the [documentation](https://worker.graphile.org/docs/library/logger).
When using the default logger, the output before would be something like this:
```
[job] INFO: Starting task
```
After:
```
[job(worker-2c04dcd6ba5728c822: someTask{1})] INFO: Starting task
```
None
None

Fix logger scope for worker

---

src/plugins/LoadTaskFromJsPlugin.ts

https://discord.com/channels/489127045289476126/498852330754801666/1194588764337610752
windows worker have issue to load, it need prefix file:/// so we using nodejs method to make sure it work on this environment
no
no

fix: window support to load worker task on library

---

RELEASE_NOTES.md
__tests__/runner.runOnce.test.ts

Follow up to #421 because I couldn't push to that branch.
- Adds release notes for:
- #415
- #421
- #424
- Clear environment in tests in case that's why one test was failing for @hiepxanh in #421
- ~~Have CI run on Windows and macOS too~~ -> moved to https://github.com/graphile/worker/pull/427

Release notes, fix env in test

---

RELEASE_NOTES.md
__tests__/runner.helpers.getTaskName.test.ts
src/helpers.ts
src/index.ts
src/interfaces.ts
src/sql/getQueueNames.ts
website/docs/tasks.md

Since we split the queue name into a separate table in 0.14, there hasn't been a "blessed" way to get the queue name of the currently executing job. This was an oversight, we weren't expecting this value to be needed but it can be useful if you want to queue another job into the same queue.
This PR adds a `getQueueName()` helper to `helpers`; e.g.
```ts
const task: Task = async (payload, helpers) => {
const queueName = await helpers.getQueueName();
console.log({queueName});
};
```
(This isn't an automatic property of `Job` because retrieving it has a performance overhead and it's not generally needed.)
Fixes #423 
Basically none unless you use it.
None known.

Add helper to get queue name of running job

---

.github/workflows/ci.yml

Fixes #419
None
Helps people who want to improve security by disabling `__proto__` on objects.

Add '--disable-proto=delete' to CI

---

RELEASE_NOTES.md
__tests__/getTasks.test.ts
src/helpers.ts
src/interfaces.ts
src/lib.ts
src/main.ts
src/sql/completeJob.ts
src/sql/failJob.ts
src/sql/getJob.ts
src/sql/getQueueNames.ts
src/sql/resetLockedAt.ts
src/taskIdentifiers.ts
src/worker.ts

Fixes #387
Marginal.
Potentially if someone can trigger deadlocks or serialization failures then this code will multiply the impact of such events. That said; I'm more concerned about the reverse (the current status) whereby it's possible for jobs to execute but fail to be released and thus be retried again later.

Give various SQL commands the ability to auto-retry on serialization failure/deadlock

---

src/lib.ts

dds EHOSTUNREACH to list of recoverable errors-
i am not sure yet what caused this error to appear, but since patching the new error code we had another failure and it was just a one-off error - the next retry worked again.
none
none

fix: add EHOSTUNREACH to list of recoverable errors

---

website/docs/config.md
website/docs/library/run.md
website/docs/library/worker-events.md
website/docs/worker-events.md

I was having trouble understanding how worker events could be used inside the configuration file. The example provided in https://github.com/graphile/worker/issues/385 helped me. 
I figured that since we were at least two not understanding how `EventEmitter` should be used, it might be useful to other to add these examples to the documentation. 
Tell me what you think of this PR :slightly_smiling_face:  
None, documentation only
None, documentation only

Documents WorkerEvents

---

RELEASE_NOTES.md
src/main.ts
src/signals.ts

Fixes #440
Specifically if we have any issues writing to stdout/stderr we trigger a graceful shutdown (and then ignore any further stdout/stderr errors because we can't really do anything about them).

Handle errors on stdout/stderr

---

website/docs/library/add-job.md

Specifying a `queueName` argument in `addJob()` (library mode) will cause jobs to be processed sequentially, one by one. This happens even if you set a value for `concurrency` in `RunnerOptions`.  The documentation for adding jobs via SQL explicitly clarifies this behavior, but it's not readily apparent when using `queueName` in library mode.
None
None

Docs: Clarify usage of queueName in addJob()

---

RELEASE_NOTES.md
__tests__/main.runTaskListOnce.test.ts
__tests__/resetLockedAt.test.ts
__tests__/workerUtils.cleanup.test.ts
__tests__/workerUtils.forceUnlockWorkers.test.ts
src/interfaces.ts
src/main.ts
src/sql/completeJob.ts
src/sql/failJob.ts
src/sql/getJob.ts
src/worker.ts
website/docs/jobs-view.md
website/docs/pro/migration.md

Using the workerId is severely limiting, and doesn't give us many advantages. By switching to using the poolId we can lay the groundwork for batched processing of jobs.
One major issue with this is that `force_unlock_workers` is now poorly named; it should be `force_unlock_pools`.
None.
None known.

Use poolId rather than workerId when locking/unlocking jobs

---

RELEASE_NOTES.md
src/plugins/LoadTaskFromExecutableFilePlugin.ts

[Discord message about this bug](https://discord.com/channels/489127045289476126/498852330754801666/1249362909553885207)
There is no performance impact
There is no security impact

Fixed standard output from child process

---

src/migrate.ts
website/docs/schema.md

This PR add doc for using a postgresql with limited user (no create rights on database) with graphile-worker
None
unknown

doc: document usage of a limited postgresql user

---

website/docs/cron.md

The 0.14 release renamed "pattern" to "match", and the doc didn't get the memo.
It looks like the new "match" field can also take a `CronMatcher`, but I'm not sure how that works.
https://github.com/graphile/worker/blob/414b11cb2a7eff0459462fd5d788d821b33f406b/src/interfaces.ts#L370

Update doc ('pattern' -> 'match')

---

RELEASE_NOTES.md
__tests__/helpers.ts
__tests__/migrate.test.ts
__tests__/resetLockedAt.test.ts
__tests__/workerUtils.cleanup.test.ts
__tests__/workerUtils.forceUnlockWorkers.test.ts
src/migrate.ts

Something most people would generally only hit if running multiple workers in CI, if at all.
Marginal cost on initial migration.
None known.

Fix race condition when multiple workers initiate database

---

RELEASE_NOTES.md
src/lib.ts
website/src/pages/errors/peh.md

If you pass a pool to Graphile Worker, that pool _ought_ to have error handlers. We've done this for you in the past, but that can result in adding lots of error handlers to the pool. Now we only add the error handlers if there aren't already any, plus we tell you that you should be doing it yourself.
Negligible startup cost.
Improvement: encouraging users to handle their own errors.

Make error handling more explicit, and warn user if they haven't

---

RELEASE_NOTES.md
__tests__/getTasks.test.ts
__tests__/helpers.ts
__tests__/main.runTaskList.test.ts
__tests__/runner.runOnce.test.ts
package.json
src/helpers.ts
src/interfaces.ts
src/main.ts
src/worker.ts
website/docs/tasks.md
yarn.lock

Still experimental; this allows you to `await Promise.race([helpers.abortPromise, doTheThing()])` in your jobs, and have the timeout/abort fire conveniently.
Extracted from #474 
Negligible - we construct it up top and it's shared by all tasks (not created on a per-task basis).
None that I can think of :thinking:

Add `abortPromise` as a helper alongside `abortSignal`

---

website/docs/contributing.md

The test command referenced in this doc page relies on the contributor using yarn. npm2yarn shows examples in npm and pnpm which suggests that npm and pnpm will work. They do not work, at least for me. It won't install successfully with npm. pnpm will install, but the test command fails.
```sh
npm install
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: graphile-worker@0.16.6
npm error Found: react@18.2.0
npm error node_modules/react
npm error   dev react@"^18.2.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^16.8.4 || ^17.0.0" from @docusaurus/core@2.4.3
npm error node_modules/@docusaurus/core
npm error   dev @docusaurus/core@"2.4.3" from the root project
npm error
npm error …
```

Remove npm2yarn in contributing doc page

---

RELEASE_NOTES.md
__tests__/crontab.test.ts
src/crontab.ts
src/interfaces.ts

Addresses https://github.com/graphile/worker/issues/495
This allows users to not specify a backfill period, and worker will default it to zero. To support this, `parseCronItem()` also now defaults it to zero in addition to `parseCrontabOptions()`
This PR changes the external interface, but it should be backwards-compatible with existing usage.
I don't expect there would be any performance impact. There is almost no runtime code changed.
Similarly, there should not be any impact to security considerations.

make backfillPeriod optional in exported CronItem type

---

Dockerfile.dev
docker-compose.yml
package.json
website/docs/contributing.md

Did an overhaul on Contributing docs to make them up-to-date with the latest changes and provide info on the things I had to figure out myself.
I also fixed the `yarn website` script, which was not working, and I added the `yarn cli` script. I'm not deeply opinionated about having yarn cli, so if you think it's not useful enough to add to package.json scripts, I'm happy to update it and update the docs.
Also, when I ran docker compose I got this warning, so I removed the version line as instructed.
```
WARN[0000] /path/to/graphile/worker/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
```

contributing documentation overhaul

---

package.json
scripts/options.mjs
src/index.ts
website/docs/config.md
yarn.lock

The `yarn website:update` command wasn't running reliably, so I've fixed it to build in an external (temp) folder.
Previously we accepted some changes to the docs in a position that gets overwritten by the above script, so I've moved those docs back to their original locations, and fixed the links to work from there.
~~I've also upgraded TypeScript and the `graphile` command.~~

Update options script to reliably fetch options

---

src/index.ts
src/interfaces.ts
website/docs/config.md
website/docs/tasks.md

Also including a couple small followups to the config documentation tweaks

tweaks to tasks documentation for clarity and consistency

---

.well-known/funding-manifest-urls

As discussed, looks like we need a `.well-known` for the repo in general too, works with PR https://github.com/graphile/graphile.github.io/pull/424

funding: well-known file

---

RELEASE_NOTES.md
__tests__/__snapshots__/crontab.test.ts.snap
__tests__/crontab.test.ts
src/cronConstants.ts

Implementation of the #542, allow nested folder task declarations in the crontab.
unkown
unknown

Add nested folder capability for crontab tasks

---

src/cron.ts
src/interfaces.ts
src/runner.ts

Currently if cron is running and the database connection goes away, it's likely that cron will bring down the entire worker instance from the inside on the next minute tickover.
This PR changes this, cron now handles its own errors via exponential backoff. This does mean that if there are bugs in cron then those errors will be logged but won't cause the system to exit, but it's necessary to be resilient to connection failure.
In future we should filter errors on expected connection error codes but enumerating those is quite tough:
- ENOENT (unix socket doesn't exist)
- ECONNREFUSED
- ETIMEDOUT
- EHOSTUNREACH
- EAI_AGAIN
- ECONNRESET
- EPIPE
- errors relating to SSL
- Regular PG errors relating to system administration (e.g. `57P03` for recovery, `53300` for too many connections, etc)
- …

Cron error recovery
