README.md
src/cli.ts
src/config.ts
src/interfaces.ts
src/worker.ts

idleDelay -> pollInterval

---

.gitignore
examples/README.md
examples/worker-faktory-exporter/README.md
examples/worker-faktory-exporter/tasks/faktory-exporter.js

* I experimented with exporting Postgres `NOTIFY` events to  [Faktory](https://github.com/contribsys/faktory) because I could not find a Postgres job queue that would meet my needs. So this is a rip-off from that work.
* I was not quite sure I a task function should throw on an error or return something to fail the job...

Add example for Faktory #7

---

README.md

Document library usage

---

.travis.yml

* I was tinkering with different Postgres versions on Travis CI in another project and come up with this
* This PR tests Postgres 9.6, 10 and 11 with Node.Js 10 and 12.
* Maybe this helps

travis test matrix

---

.travis.yml

* Postgres 12 is released :tada: 
* Maybe this is a little bit "over the top" with all the different versions - but I introduced this in a prior PR, so here it goes.

Add postgresql 12 to ci grid

---

src/getTasks.ts
src/main.ts
src/worker.ts
yarn.lock

Fixes #38  
Fixes #39  
Fixes #40  
Fixes #41

Reset yarn lockfile

---

README.md

Sorry this simple update took a while 👀

Adds link to issue explaining how to fix `pgcrypto` not installed in public

---

README.md

Thank you to all our Featured Sponsors, past and present, for supporting our work 🤩

Update README.md for sponsorship update

---

README.md
__tests__/reset-db.sql
src/migrate.ts

fix(db): remove 'uuid-ossp' requirement

---

__tests__/helpers.ts
src/interfaces.ts
src/logger.ts

fix(types): jobId is a string

---

__tests__/main.runTaskListOnce.test.ts
__tests__/migrate.test.ts
sql/000003.sql

Before:
```
Timing startup/shutdown time...
... it took 67ms
Scheduling 20000 jobs
Timing 20000 job execution...
Found 999!
... it took 3210ms
Jobs per second: 6363.16
Testing latency...
[core] INFO: Worker connected and looking for jobs... (task names: 'latency')
Beginning latency test
Latencies - min: 2.47ms, max: 12.00ms, avg: 2.72ms
Done
Done in 10.52s.
```
After:
```
Timing startup/shutdown time...
... it took 65ms
Scheduling 20000 jobs
Timing 20000 job execution...
Found 999!
... it took 2033ms
Jobs per second: 10165.04
Testing latency...
[core] INFO: Worker connected and looking for jobs... (task names: 'latency')
Beginning latency test
Latencies - min: 2.42ms, max: 12.37ms, avg: 2.71ms
Done
Done in 9.03s.
```

feat(perf): allow queue_name to be null

---

src/worker.ts

Ref: https://www.reddit.com/r/node/comments/f085tz/graphile_worker_low_latency_postgresqlbacked_job/fgsfnpw/

fix: decrease chance of worker ID collision

---

README.md
src/interfaces.ts
src/main.ts

feat: add ability to turn off signal handlers

---

tsconfig.json

see for details https://stackoverflow.com/questions/51716406/typescript-tsconfig-settings-for-node-js-10

chore: optimize tsconfig.json for node 10

---

sql/000001.sql
sql/000002.sql

This PR only adds whitespace. Formatting to make analysis such as that in #94 easier.

chore: prettify old migrations

---

README.md
SPONSORS.md

Here is the sponsorship update for April, with a new `sponsors.md` file. This is the first time I've done this through a script, so there are some formatting changes too. 
✨Thank you to each and every sponsor of Graphile, your donations are helping us to keep working during the pandemic ✨

sponsorship: update sponsors for April ❤️

---

.github/workflows/ci.yml
package.json
yarn.lock

chore: update pg version range for Node 14 support

---

SPONSORS.md

Here is the sponsorship update for May. We have a spots open for a Featured Sponsor and Project Sponsors, please [contact us on Discord](http://discord.gg/graphile) if your company is interested.
✨Thank you to each and every sponsor of Graphile, your donations are helping us to keep working during the pandemic ✨

sponsorship: update sponsors for May 🙌

---

Dockerfile
Dockerfile.dev
README.md
docker-compose.yml

#85 
* Adapted multi-stage commits from Postgraphile
* Added some docs
* Tasks are added via volume mount

docker: official Docker image

---

__tests__/forbiddenFlags.test.ts
__tests__/helpers.ts
__tests__/migrate.test.ts
__tests__/schema.sql
sql/000005.sql
src/helpers.ts
src/interfaces.ts
src/worker.ts

This is a modified version of #128.

feat: forbidden flags

---

README.md
src/interfaces.ts

docs: fix description of priority

---

README.md
src/interfaces.ts

docs: document Forbidden Flags feature

---

RELEASE_NOTES.md
package.json

Can track release notes as we go this way.

chore: add release notes "pending" section

---

README.md

This is a little tricky if you don’t have the right pg version running already

docs: add note regarding the required db dump step

---

src/main.ts
src/worker.ts

This PR just reorders some variable definitions/etc, it should have no material effect on the running of worker; but it will simplify the diff of #155.
None.
None.

chore(refactor): move some logic about

---

examples/README.md
examples/worker-bullmq-exporter/README.md
examples/worker-bullmq-exporter/tasks/bullmq-exporter.js

Added an example of how to export tasks to [BullMQ](https://github.com/taskforcesh/bullmq), similar to the other two examples.
n/a
Well, I guess it get's out of your control at this point ;)

docs(examples): add bullmq-exporter

---

README.md
src/interfaces.ts
src/worker.ts

Adds error to the job:complete event. 
yarn test passes, but I did not change the tests. 
Minimal
Nill

feat(events): add error to job:complete event

---

__tests__/schema.sql
scripts/dump_db

It serves no benefit and makes PRs more noisy.

chore: remove ownership from DB dump

---

README.md
__tests__/fixtures/tasks/wouldyoulike.js
__tests__/helpers.ts
src/cron.ts

Document logger, and move more messages to logger.debug.
Negligible.
None known.

chore(logs): reduce logging

---

RELEASE_NOTES.md
src/lib.ts
src/main.ts
src/signals.ts

- No longer handles SIGPIPE (lets Node swallow it)
- Ensures client releases error handler once used
- Fixes an uncaught promise rejection error
Negligible.
Slight improvement?

fix(errors): overhaul error handling

---

README.md

Fix markdown typo in README

---

README.md

docs: add note about distributed crontab

---

README.md
RELEASE_NOTES.md
__tests__/migrate.test.ts
__tests__/schema.sql
sql/000001.sql
sql/000002.sql
sql/000010.sql
src/migrate.ts

Alternative to/supersedes #251, as per [comment](https://github.com/graphile/worker/pull/251#issuecomment-1106608649). Fixes #249.
I only edited the existing migrations the minimum amount to prevent them from failing. It's probably possible to remove large parts of the old cruft, but as you are no doubt aware, the idea of migrations is not to edit them later (ideally), and you would have to be more careful not to break users upgrading from an old version, so I didn't attempt that.
unknown
unknown

feat(deps): remove dependency on gen_random_uuid()/pgcrypto

---

README.md

Tiny `README` enhancement to resolve #266.

docs(readme): Clarify `maxAttempts`

---

README.md
SPONSORS.md

A sponsor's update for June for the website. Thank you to all our sponsors, past and present ❤️
N/A
N/A
~- [ ] I've added tests for the new feature, and `yarn test` passes.~
~- [ ] I have detailed the new feature in the relevant documentation.~
~- [ ] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).~
~- [ ] If this is a breaking change I've explained why.~

sponsorship: update sponsors 💙

---

__tests__/cron.test.ts
__tests__/cronMatcher.test.ts
src/cronMatcher.ts
src/crontab.ts
src/interfaces.ts

This is #250 but with the two additional fixes applied; unfortunately I was unable to push to the source branch so I've raised a separate PR. Please see #250 for discussion/etc.
Fixes #250

chore: internal refactor of cron

---

README.md

Fixes #203; see that issue for reasoning.
None.
None.

chore: remove experimental flag from cron

---

__tests__/events.test.ts
__tests__/main.runTaskList.test.ts
__tests__/main.runTaskListOnce.test.ts

chore(tests): make more resilient to deferreds

---

__tests__/forbiddenFlags.test.ts
__tests__/helpers.ts
__tests__/main.runTaskListOnce.test.ts
__tests__/migrate.test.ts
__tests__/workerUtils.addJob.test.ts
__tests__/workerUtils.completeJobs.test.ts
__tests__/workerUtils.permanentlyFailJobs.test.ts
__tests__/workerUtils.rescheduleJobs.test.ts

chore(tests): consistently use getJobs/getJobQueues

---

perfTest/init.js
perfTest/run.js
perfTest/tasks/stuck.js

chore: update perfTest

---

README.md
SPONSORS.md

Sponsors update for Summer 2022, thank you everyone for your support ❤️

sponsorship: update sponsors 😻

---

__tests__/batchJobs.test.ts

Somehow left this out of #286 
None.
None.

chore: add tests for new batchJobs feature

---

src/main.ts
src/sql/failJob.ts

Graceful shutdown was failing because it was attempting to call the `fail_job` function that no longer exists. This PR replaces that behavior
None.
None.

fix: fail_job function no longer exists

---

README.md
SPONSORS.md

A Winter 2022 sponsor's update, thank you for all of your support everyone! ✨
Pssst if you haven't seen it yet, you might be interested in our recent conference talk about some of the things coming up next year, which wouldn't have been possible without our sponsors' support 💖 https://youtu.be/x0FMjL5-kNI

sponsorship: update sponsors ❤️

---

.github/workflows/docker-hub.yaml
Dockerfile

Fixes #311 
Auto-publish to Docker Hub

Add Docker Hub action

---

__tests__/main.runTaskListOnce.test.ts

Just another tweak due to test task inconsistency.

job1 -> job3

---

RELEASE_NOTES.md
src/cron.ts
src/interfaces.ts

Add more detail to cron:backfill event

---

website/README.md
website/docs/index.md
website/docs/requirements.md
website/docs/tasks.md

Beginning editorial work on the worker website: checking links, formatting etc as well as adding a readme file

website: Editorial

---

website/docs/glossary.md

website: Add a glossary page

---

website/docs/faq.md
website/docs/scaling.md

website: Add FAQ and Scaling pages

---

website/docs/schema.md

Add article explaining not to read from the 'jobs' table

---

src/index.ts
src/logger.ts

Export LogLevel as a type

---

website/docs/admin-functions.md

Sorry for deleting the rest of items in this PR template, but I just fixed a link in the docs and they don't apply 😰

Fix link to worker utils

---

src/config.ts
src/index.ts
src/interfaces.ts
src/lib.ts
src/main.ts
src/migrate.ts
src/runner.ts
src/sql/completeJob.ts
src/sql/failJob.ts
src/sql/getJob.ts
src/sql/resetLockedAt.ts
src/worker.ts

Whilst backporting the plugin system to 0.13.x I discovered some issues in the newly introduced hooks. This PR forward-ports the fixes that I applied to that branch.
Negligible.
None known.

Forward-port fixes from back-port of plugin system

---

RELEASE_NOTES.md
__tests__/getTasks.test.ts
__tests__/runner.runOnce.test.ts
__tests__/workerUtils.addJob.test.ts
perfTest/graphile.config.js
src/cli.ts
src/config.ts
src/cron.ts
src/getCronItems.ts
src/getTasks.ts
src/helpers.ts
src/index.ts
src/interfaces.ts
src/lib.ts
src/main.ts
src/preset.ts
src/runner.ts
src/sql/completeJob.ts
src/sql/failJob.ts
src/sql/getJob.ts
src/sql/resetLockedAt.ts
src/worker.ts
src/workerUtils.ts

I backported v0.16 back into v0.13 in #392; in doing so I discovered and fixed a number of issues and deficiencies. This PR merges these fixes back into v0.16.
Unknown.
Unknown.

Forward-port back-port fixes

---

RELEASE_NOTES.md
website/docs/config.md
website/docs/pro/config.md
website/docs/pro/index.md
website/docs/pro/migration.md
website/docs/pro/recovery.md
website/docusaurus.config.js
website/src/pages/releases.mdx

Worker Pro is a new proprietary (not open source) plugin for Graphile Worker that enables optional features that users may appreciate, particularly useful to larger deployments.
This initial version only implements the migration aid functionality, more functionality is planned.
PR is documentation only.
PR is documentation only.

Worker Pro documentation

---

website/news/2023-12-11-016-release.mdx

Small date fix before we share this article around

website: News date fix

---

website/src/components/SponsorButtons/styles.module.css
website/src/pages/sponsors.mdx

- Spring Sponsor update :star-struck: Thank you to all our sponsors, past and present
- A couple edits to the wider sponsor page
NA
NA

website: Sponsor update

---

src/lib.ts

we experienced a downtime this morning after which the db was restarted. unfortunately, the queue was not restarted because "cannot connect now" is not retryable. this pr adds the respective error code to the list of retryable errors with a backoff time of 3s. retryable errors is now a list of object that holds the code and the backoff time
Edit: we have had another crash since this patch was applied and the queue recovered just fine. the crash was caused by a segfault.
unknown, probably none.
unknown, probably none.

feat: add "cannot connect now" to list of retryable errors

---

package.json
website/docusaurus.config.js
website/package.json
website/src/css/common.module.css
website/src/pages/pricing.mdx
website/src/pages/pricing.module.css
website/src/theme/MDXComponents.jsx
yarn.lock

A Pro page (mirroring the one found on [PostGraphile.org](https://postraphile.org/pro) (https://github.com/graphile/crystal/pull/1964)
- responsive
- dark mode
- navbar link
- sponsor badge for use in docs
- launch offer at $25 / mo
Some images
Tooltips
Dark mode mobile view

website: Pro Page

---

website/docs/admin-functions.md

Fixes mistake raised in https://github.com/graphile/worker/pull/415#issuecomment-1980723703

Apply fix to cleanup docs

---

src/lib.ts

adds timeout to list of recoverable errors.

feat: recover on timeout

---

website/docs/faq.md

docs only - just a few typos I noticed
N/A
N/A

docs: fix typos in FAQ

---

RELEASE_NOTES.md
__tests__/workerUtils.cleanup.test.ts
src/cleanup.ts

Fix cleanup command

---

RELEASE_NOTES.md
__tests__/workerUtils.cleanup.test.ts
src/cleanup.ts
src/cli.ts
src/interfaces.ts
src/workerUtils.ts

Cleanup now allows you to specify additional identifiers to keep

---

RELEASE_NOTES.md
src/cli.ts

Remove CLI defaults so they don't override graphile config file

---

website/src/pages/pricing.mdx
website/src/pages/sponsors.mdx

An update to the listed featured sponsors, thank you to all our sponsors, past and present 🤩
NA
NA
- ~[ ] I've added tests for the new feature, and `yarn test` passes.~
- ~[ ] I have detailed the new feature in the relevant documentation.~
- ~[ ] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).~
- ~[ ] If this is a breaking change I've explained why.~

sponsors: Update website

---

website/docs/config.md

Add an explanation around maxPoolSize based on discord conversation.
N/A
N/A
N/A - documentation only

Expand on considerations re maxPoolSize

---

RELEASE_NOTES.md
__tests__/workerUtils.addJob.test.ts
__tests__/workerUtils.addJobs.test.ts
examples/readme/events.js
src/helpers.ts
src/index.ts
src/interfaces.ts
src/lib.ts
src/workerUtils.ts
website/docs/library/add-job.md
website/docs/library/add-jobs.md
website/docs/library/index.md
website/docs/library/queue.md
website/docs/tasks.md
website/docs/typescript.md

- Fixes #508
Improvement if batching is used.
None known.

Expose addJobs function via library interface

---

.gitignore
__tests__/migrate.test.ts
__tests__/runner.helpers.getTaskName.test.ts
__tests__/runner.runOnce.test.ts
package.json
src/cron.ts
src/crontab.ts
src/deferred.ts
src/interfaces.ts
src/lib.ts
src/main.ts
src/migrate.ts
src/plugins/LoadTaskFromJsPlugin.ts
src/runner.ts
src/worker.ts
tsconfig.json
yarn.lock

Trying to make that PR more approachable.

Extract various minor enhancements from #474

---

.well-known/funding-manifest-urls
website/static/.well-known/funding-manifest-urls

funding: fix link

---

website/docs/library/queue.md

Note that addJobAdhoc is new

---

src/runner.ts

Refactor stop to handle unexpected errors

---

RELEASE_NOTES.md
src/cron.ts
src/lib.ts
src/localQueue.ts
src/main.ts
src/runner.ts
src/worker.ts

Still no idea how @psteinroe triggered #541 but I'm clutching at straws...

Use safeEmit() helper
